apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajkg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajkg
  template:
    metadata:
      labels:
        app: ajkg
    spec:
      containers:
      - image: okteto.dev/ajkg:latest
        name: ajkg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/BrainStorm-html.zip"
        - name: Vless_UUID
          value: "e632ea37-3a84-45f4-8476-18097647e748"
        - name: Vless_Path
          value: "/e632ea37-3a84-45f4-8476-18097647e748-vless"
        - name: Vmess_UUID
          value: "e632ea37-3a84-45f4-8476-18097647e748"
        - name: Vmess_Path
          value: "/e632ea37-3a84-45f4-8476-18097647e748-vmess"
        - name: Share_Path
          value: "/vnk"
